services:
  graphql-mock-server:
    build: ./
    environment:
      MOCK_SCENARIO: default
      MOCK_SEED: 12345
    ports:
      - target: 4000
        host_ip: 127.0.0.1
        published: 4000
        protocol: tcp
        mode: host
    volumes:
      - ./src:/app/src
